[[protocols]]
name = "retropie"
protocol = "nec"
variant = "nec32"
[protocols.scancodes]
0x30859060 = "KEY_X" # A
0x30859061 = "KEY_Z" # B
0x30859062 = "KEY_S" # C
0x30859063 = "KEY_A" # D
0x3085f009 = "KEY_MEDIA"
# 0x3085e010 = "KEY_POWER2" # TV Power
0x3085e011 = "KEY_TV" # Live TV
0x3085c034 = "KEY_VIDEO_NEXT" # Input
0x3085e013 = "KEY_RIGHTSHIFT" # Info
0x3085a05f = "KEY_CYCLEWINDOWS"
0x0085305f = "KEY_CYCLEWINDOWS"
0x3085c036 = "KEY_EPG" # Guide
0x3085e014 = "KEY_UP" # Up
0x3085e016 = "KEY_DOWN" # Down
0x3085e017 = "KEY_LEFT" # Left
0x3085e015 = "KEY_RIGHT" # Right
0x3085e018 = "KEY_SCROLLDOWN" # Thumbs down
0x3085e019 = "KEY_SELECT" # Select
0x3085e01a = "KEY_SCROLLUP" # Thumbs up
0x3085e01c = "KEY_VOLUMEUP" # Volume Up
0x3085e01d = "KEY_VOLUMEDOWN" # Volume Down
0x3085e01b = "KEY_MUTE"#  Mute
0x3085d020 = "KEY_RECORD" # Record
0x3085e01e = "KEY_CHANNELUP" # Channel up
0x0085301f = "KEY_CHANNELDOWN" # Channel down
0x3085e01f = "KEY_CHANNELDOWN" # Channel down
0x3085d021 = "KEY_PLAY" # Play
0x3085d023 = "KEY_PAUSE" # Pause
0x3085d025 = "KEY_SLOW" # Slow
0x3085d022 = "KEY_REWIND" # Rewind
0x3085d024 = "KEY_FASTFORWARD" # Fast Forward
0x3085d026 = "KEY_PREVIOUS" # Previous / Back
0x3085d027 = "KEY_NEXT" # Next
0x3085b044 = "KEY_ZOOM" # Zoom
0x3085b048 = "KEY_STOP"
0x3085b04a = "KEY_DVD"
0x3085d028 = "KEY_NUMERIC_1" # 1
0x3085d029 = "KEY_NUMERIC_2" # 2
0x3085d02a = "KEY_NUMERIC_3" # 3
0x3085d02b = "KEY_NUMERIC_4" # 4
0x3085d02c = "KEY_NUMERIC_5" # 5
0x3085d02d = "KEY_NUMERIC_6" # 6
0x3085d02e = "KEY_NUMERIC_7" # 7
0x3085d02f = "KEY_NUMERIC_8" # 8
0x0085302f = "KEY_NUMERIC_8" # 8
0x3085c030 = "KEY_NUMERIC_9" # 9
0x3085c031 = "KEY_NUMERIC_0" # 0
0x3085c033 = "KEY_ENTER" # Enter
0x3085c032 = "KEY_ESC" # Clear
0x3085f00c = "KEY_HOME" # Tivo
